const AppFonts = {
  poppinsBlack: 'Poppins-Black',
  poppinsBlackItalic: 'Poppins-BlackItalic',
  poppinsBold: 'Poppins-Bold',
  poppinsBoldItalic: 'Poppins-BoldItalic',
  poppinsExtraBold: 'Poppins-ExtraBold',
  poppinsExtraBoldItalic: 'Poppins-ExtraBoldItalic',
  poppinsExtraLight: 'Poppins-ExtraLight',
  poppinsExtraLightItalic: 'Poppins-ExtraLightItalic',
  poppinsItalic: 'Poppins-Italic',
  poppinsLight: 'Poppins-Light',
  poppinsLightItalic: 'Poppins-LightItalic',
  poppinsMedium: 'Poppins-Medium',
  poppinsMediumItalic: 'Poppins-MediumItalic',
  poppinsRegular: 'Poppins-Regular',
  poppinsSemiBold: 'Poppins-SemiBold',
  poppinsSemiBoldItalic: 'Poppins-SemiBoldItalic',
  poppinsThin: 'Poppins-Thin',
  poppinsThinItalic: 'Poppins-ThinItalic',
  robotoSerifBold: 'RobotoSerif-Bold',
  robotoSerifRegular: 'RobotoSerif-Regular',
  robotoSerifBlack: 'RobotoSerif-Black',
  RobotoSerifMedium: 'RobotoSerif-Medium',
  robotoThinItalic: 'Roboto-ThinItalic',
  robotoThin: 'Roboto-Thin',
  robotoMediumItalic: 'Roboto-MediumItalic',
  robotoRegular: 'Roboto-Regular',
  robotoMedium: 'Roboto-Medium',
  robotoLightItalic: 'Roboto-LightItalic',
  robotoLight: 'Roboto-Light',
  robotoItalic: 'Roboto-Italic',
  robotoBoldItalic: 'Roboto-BoldItalic',
  robotoBold: 'Roboto-Bold',
  robotoBlackItalic: 'Roboto-BlackItalic',
  robotoBlack: 'Roboto-Black',
};

export default AppFonts;
